version: "3.1"
services:
  api-server:
    image: graphql-node
    restart: always
    ports:
      - "1234:1234"
    depends_on:
      - mongo
    external_links:
      - mongo
    networks:
      - note-mern-app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - note-mern-app
    volumes:
      - mongo-data:/data/db
networks:
  note-mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
